# !! THIS FILE IS AUTOMATICALLY GENERATED.
# DO NOT EDIT. 
# SEE simplificationtermhelper.py
def ClCHm() -> float:
    pass
def DlDHm() -> float:
    pass
def ClCmCHlCHmDlDHm() -> float:
    pass
def ClCHmDlDmDHlDHm() -> float:
    pass
def ClCHlDlDHm() -> float:
    pass
def CmCHmDlDHm() -> float:
    pass
def ClCHmDlDHl() -> float:
    pass
def ClCHmDmDHm() -> float:
    pass
